services:
  - type: web
    name: fiskal-api
    plan: free
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DB_ENGINE
        value: "mysql"
      - key: DB_HOST
        value: "mysql-172e2dac-kaleth951-be8c.c.aivencloud.com"
      - key: DB_PORT
        value: "25666"
      - key: DB_USER
        value: "avnadmin"
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: "defaultdb"
